import mongoose, { SchemaType } from "mongoose";
const HotelSchema=new mongoose.Schema({
    ownerName:{
        type:String,
        required:true
    },
    hotelDescription:{
        type:String,
        required:true
    },
    hotelLocation:{
        type:String,
        required:true
    },
    hotelName:{
        type:String,
        required:true
    },
    hotelImages:{
        type:[String],
        required:true
    },
    propertyType:{
        type:String,
        required:true
    },
    verified:{
        type:Boolean,
        default:false
    },
    VerificationDocuments:{
        type:[String],
        required:true
    },
    contactNumber:{
        type:String,
        required:true
    },
    isactive:{
        type:Boolean,
        default:false
    },
    facilities:{
        type:[String],
        required:true
    },
    checkinTime:{
        type:String,
        required:true
    },
    checkoutTime:{
        type:String,
        required:true
    },
    pricePerNight:{
        type:Number,
        required:true
    },
    rating:{
        type:Number,
        default:0
    },
    numberOfReviews:{
        type:Number,
        default:0
    },


},{timestamps:true})

export const hotelModel=mongoose.model('hotels',HotelSchema);